server:
  port: 9005
  servlet:
    address: localhost
    encoding:
      enabled: true
      force: true
      charset: UTF-8

    http2:
    enabled: true
    context-path: /api

  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel:
      enabled: true

spring:

  cloud:
    config:
      enabled: false

  application:
    name: team-service      # Application name

  profiles:
    default: default

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
    password: lovesignal

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/love?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy

  cloud:
    config:
      enabled: false

swagger:
  enable: true      # Use Swagger


logging:
  level:
    org.hibernate.type: trace     # Show Query Parameter

redis-key:
  block-user: block_user
  matching-male-user: matching_male_user
  matching-male-waiting: matching_female_waiting
  matching-female-user: matching_female_user
  matching-female-waiting: matching_female_waiting
  recent-teams: recent_teams

redis-expire:
  recent-team: 600
  block-user: 600