server:
  port: 0
  ssl:
    enabled: false
  servlet:
    context-path: /api

spring:
  application:
    name: team-service

#  config:
#    import: "optional:configserver:http://13.125.99.25:8888/"
#  cloud:
#    config:
#      name: mysql,redis
#      profile: config

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8b309.p.ssafy.io:3306/love?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: lovesignal
    password: lovesignal

  cache:
    type: redis
  redis:
    host: 13.125.99.25
    port: 6379
    password: lovesignal

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

redis-key:
  block-user: block_user
  matching-male-user: matching_male_user
  matching-male-waiting: matching_male_waiting
  matching-female-user: matching_female_user
  matching-female-waiting: matching_female_waiting
  recent-teams: recent_teams

redis-expire:
  recent-team: 60
  block-user: 60

