server:
  port: 9005
  servlet:
    address: localhost
    encoding:
      enabled: true
      force: true
      charset: UTF-8

    http2:
    enabled: true

  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel:
      enabled: true

spring:

  application:
    name: team-service      # Application name

  profiles:
    default: default

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      passoword: lovesignal

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/love?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy

swagger:
  enable: true      # Use Swagger


logging:
  level:
    org.hibernate.type: trace     # Show Query Parameter