server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kwnoyng/LoveSignal-Config.git
#          username:
#          password: