version: "3"

services:
  frontend:
    build:
      context: ./love-signal-pwa
      dockerfile: Dockerfile
    volumes:
      - build:/app/build
    command: "npm run start"
    working_dir: /app

volumes:
  build:
