version: "3"

services:
  frontend:
    build:
      context: ./love_signal
      dockerfile: Dockerfile
    volumes:
      - build:/app/build
    environment:
      - GENERATE_SOURCEMAP=false
    command: "npm run start"
    working_dir: /app

volumes:
  build:
