server:
  port: 8000

logging:
  level:
    root: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8b309.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway
#  cloud:
#    gateway:
#      routes:
#        - id: member-service
#          uri: lb://member-service
#          predicates:
#            - Path=/member/**
#          filter:
#            - AuthenticationGatewayFilterFactory
#
#        - id: team-service
#          uri: lb://team-service
#          predicates:
#            - Path=/team/**
#          filter:
#            - AuthenticationGatewayFilterFactory
#
#        - id: chatting-service
#          uri: lb://chatting-service
#          predicates:
#            - Path=/chatting/**
#          filter:
#            - AuthenticationGatewayFilterFactory
#
#        - id: file-service
#          uri: lb://file-service
#          predicates:
#            - Path=/file/**
#          filter:
#            - AuthenticationGatewayFilterFactory
#
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**

  security:
    oauth2:
      client:
        kakao:
          account-uri: https://kapi.kakao.com/v2/user/me?property_keys=["for_partner.uuid"]
