server:
  port: 8000

logging:
  level:
    root: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/**
          filters:
            - name : Authentication

        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/team/**
          filters:
            - name: Authentication

        - id: chatting-service
          uri: lb://chatting-service
          predicates:
            - Path=/chat/** , /chatRoom/**, /ws-stomp/**, /pub/**, /sub/**, /webjars/**
#          filters:
#            - name: Authentication

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
          filters:
            - name: Authentication

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - https://www.love-signal.kr
            allow-credentials: true
            allowedHeaders:
              - Access-Control-Allow-Credentials
              - Access-Control-Allow-Origin
              - X-Auth_Token
              - X-Auth_ID
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

  security:
    oauth2:
      client:
        kakao:
          account-uri: https://kapi.kakao.com/v2/user/me?property_keys=["for_partner.uuid"]
