server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k8b309.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/**
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/team/**
        - id: chatting-service
          uri: lb://chatting-service
          predicates:
            - Path=/chatting/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
