server:
  port: 8000

logging:
  level:
    root: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/**
          filters:
            - name : AuthenticationGatewayFilterFactory

        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/team/**

        - id: chatting-service
          uri: lb://chatting-service
          predicates:
            - Path=/chat/**
            - Path=/chatRoom/**

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - https://www.love-signal.kr
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS


  security:
    oauth2:
      client:
        kakao:
          account-uri: https://kapi.kakao.com/v2/user/me?property_keys=["for_partner.uuid"]
