server:
  port: 0
  ssl:
    enabled: false
  servlet:
    context-path: /api

cloud:
  aws:
    credentials:
      accessKey: AKIA4VGHNPMWWMP3DJPX
      secretKey: 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
    s3:
      bucket: love-signal
      profile-path: profile/
      chatfile-path: chatfile/
      default-profile: https://love-signal.s3.ap-northeast-2.amazonaws.com/default-blob
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  application:
    name: file-service

#  config:
#    import: "optional:configserver:http://13.125.99.25:8888/"
#  cloud:
#    config:
#      name: mysql,s3
#      profile: config

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8b309.p.ssafy.io:3306/love?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: lovesignal
    password: lovesignal

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


