cloud:
  aws:
    credentials:
      accessKey: AKIA4VGHNPMWWMP3DJPX
      secretKey: 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
    s3:
      bucket: love-signal
      profile-path: profile/
      chatfile-path: chatfile/
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 9010
  servlet:
    address: localhost
    encoding:
      enabled: true
      force: true
      charset: UTF-8

    http2:
    enabled: true
    context-path: /api

  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel:
      enabled: true

spring:

  application:
    name: file-service      # Application name

  profiles:
    default: default

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/love?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0

  cloud:
    config:
      enabled: false

swagger:
  enable: true      # Use Swagger


logging:
  level:
    org.hibernate.type: trace     # Show Query Parameter\


