server:
  port: 9999
  ssl:
    enabled: false

spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        kakao:
          token-uri: https://kauth.kakao.com/oauth/token
          account-uri: https://kapi.kakao.com/v2/user/me?property_keys=["for_partner.uuid", "kakao_account.email"]
          logout-uri: https://kapi.kakao.com/v1/user/logout
          #          redirect-uri: https://www.love-signal.kr/signup
          redirect-uri: http://localhost:3000/signup
          client-id: 0bae6bcf8c40843c797b0bb3025272d5
  #  config:
  #    import: "optional:configserver:http://13.125.99.25:8888/"
  #  cloud:
  #    config:
  #      name: mysql
  #      profile: config

  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://k8b309.p.ssafy.io:3306/love?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  #   username: lovesignal
  #   password: lovesignal

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
