server:
  port: 8888
  servlet:
    address: localhost
    encoding:
      enabled: true
      force: true
      charset: UTF-8

    http2:
    enabled: true

  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel:
      enabled: true

spring:

  application:
    name: auth-service      # Application name

  profiles:
    default: default

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  jpa:
#    hibernate:
#      ddl-auto: none
#    generate-ddl: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/love?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
#    username: root
#    password: ssafy

  security:
    oauth2:
      client:
        kakao:
          token-uri: https://kauth.kakao.com/oauth/token
          account-uri: https://kapi.kakao.com/v2/user/me?property_keys=["for_partner.uuid", "kakao_account.email"]
          logout-uri: https://kapi.kakao.com/v1/user/logout
#          redirect-uri: https://www.love-signal.kr/signup
          redirect-uri: http://localhost:3000/signup
          client-id: 0bae6bcf8c40843c797b0bb3025272d5
  cloud:
    config:
      enabled: false

swagger:
  enable: true      # Use Swagger


logging:
  level:
    org.hibernate.type: trace     # Show Query Parameter
