server:
  port: 4444

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://discoveryservice:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
